# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Header Bar V1"
  description:
  icon: bottom_navigation
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  logo_text: LOGO
  logo_url: /

  links:
    - text: Headers
      url: "#"
    - text: Banners
      url: "#"
    - text: Link
      url: "#"

  cta_text: Link
  cta_url: "#"
  cta_class: button

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
